/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Surfaces — pointent vers des CSS variables pour le theming ──
        "background":                  "var(--color-background)",
        "surface":                     "var(--color-surface)",
        "surface-bright":              "var(--color-surface-bright)",
        "surface-dim":                 "var(--color-surface-dim)",
        "surface-container-lowest":    "var(--color-surface-container-lowest)",
        "surface-container-low":       "var(--color-surface-container-low)",
        "surface-container":           "var(--color-surface-container)",
        "surface-container-high":      "var(--color-surface-container-high)",
        "surface-container-highest":   "var(--color-surface-container-highest)",
        "surface-variant":             "var(--color-surface-variant)",
        "on-surface":                  "var(--color-on-surface)",
        "on-surface-variant":          "var(--color-on-surface-variant)",
        "outline":                     "var(--color-outline)",
        "outline-variant":             "var(--color-outline-variant)",

        // ── Couleurs fixes (identiques clair/sombre) ──
        "on-tertiary-container": "#67f4b7",
        "error-container": "#ffdad6",
        "secondary-container": "#39b8fd",
        "tertiary": "#005338",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001e2f",
        "on-secondary-fixed-variant": "#004c6e",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#002113",
        "secondary-fixed-dim": "#89ceff",
        "on-tertiary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3323cc",
        "primary-container": "#4f46e5",
        "tertiary-container": "#006e4b",
        "on-secondary-container": "#004666",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "on-background": "var(--color-on-surface)",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "secondary-fixed": "#c9e6ff",
        "inverse-primary": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "primary": "#3525cd",
        "secondary": "#006591",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#0f0069",
        "surface-dim-fixed": "#cbdbf5",
        "on-primary-fixed-var": "#3323cc",
        "on-secondary-fixed-var": "#004c6e",
        "inverse-on-surface": "#eaf1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.25rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
      boxShadow: {
        "xs": "0 1px 2px rgba(0,0,0,0.04)",
        "sm": "0 1px 8px rgba(0,0,0,0.04)",
        "md": "0 4px 24px -4px rgba(79,70,229,0.08), 0 1px 3px rgba(15,23,42,0.04)",
        "primary-glow": "0 0 0 1px rgba(79,70,229,0.15), 0 4px 20px -2px rgba(14,165,233,0.12)",
      },
    },
  },
  plugins: [],
};
